deviceProviders:
  zigbee:
    ip: 192.168.1.180
    baseTopic: zigbee2mqtt
  logo:
    ip: 192.168.1.200
    port: 510
    pollingInterval: 60000
    outputsAddress: 8192
    switchReturnTime: 100
    devices:
      - name: Lights hallway
        switchAddress: 8256
        outputNumber: 1
      - name: Lights garage
        switchAddress: 8257
        outputNumber: 2
  hue:
    apiKey: xxx
    polling:
      minPollInterval: 1000
      maxPollInterval: 60000
      backOffInterval: 120000
      backOffFactor: 2
  solaredge:
    site: xxx
    apiKey: xxx
  tuya:
    devices:
      - name: Verwarming bureau
        type: fancoil
        ip: 192.168.2.217
        id: bfb5c321632e97e066ua7v
        key: xxx
      - name: Verwarming slaapkamer
        type: fancoil
        ip: 192.168.2.197
        id: bfc25428abdae57f82kwdp
        key: xxx
      - name: Verwarming Tine's crib
        type: fancoil
        ip: 192.168.2.193
        id: bfdaafe7a17a881374fwfd
        key: xxx
      - name: Verwarming kinderkamer
        type: fancoil
        ip: 192.168.2.77
        id: bf5c398cf43a8c5cf5q2dm
        key: xxx
home:
  rooms:
    - id: livingroom
      name: Living
    - id: kitchen
      name: Keuken
    - id: kidsroom
      name: Kinderkamer
    - id: bedroom
      name: Slaapkamer
    - id: tine
      name: Tine's crib
    - id: office
      name: Bureau
    - id: hallway
      name: Hal
    - id: garage
      name: Garage
    - id: laundry
      name: Wasruimte
    - id: basement
      name: Kelder
    - id: shaft
      name: Koker
    - id: toilet
      name: WC
    - id: bathroom
      name: Badkamer
    - id: attic
      name: Zolder
    - id: storage
      name: Berging
    - id: outside
      name: Buiten
    - id: shed
      name: Tuinhuis
  devices:
    - deviceId: ZIGBEE-0x00158d0006d0ba73
      friendlyId: button-hallway
      roomId: hallway
    - deviceId: ZIGBEE-0xb4e3f9fffe67d474
      friendlyId: button-garage
      roomId: garage
    - deviceId: ZIGBEE-0x00158d0006c6e6e6
      friendlyId: sensor-living
      roomId: livingroom
    - deviceId: ZIGBEE-0x00158d00091c2406
      friendlyId: sensor-laundry
      roomId: laundry
    - deviceId: ZIGBEE-0x00158d00091a418c
      friendlyId: sensor-basement
      roomId: basement
    - deviceId: ZIGBEE-0x00158d00091ad72f
      friendlyId: sensor-kitchen
      roomId: kitchen
    - deviceId: ZIGBEE-0x00158d00091c22ea
      friendlyId: sensor-shaft
      roomId: shaft
    - deviceId: ZIGBEE-0x00158d000941118d
      friendlyId: sensor-hallway-downstairs
      roomId: hallway
    - deviceId: ZIGBEE-0x00158d00091adbf3
      friendlyId: sensor-office
      roomId: office
    - deviceId: ZIGBEE-0x00158d00091c261d
      friendlyId: sensor-toilet
      roomId: toilet
    - deviceId: ZIGBEE-0x00158d00091c8153
      friendlyId: sensor-garage
      roomId: garage
    - deviceId: ZIGBEE-0x00158d00091a41f9
      friendlyId: sensor-kidsroom
      roomId: kidsroom
    - deviceId: ZIGBEE-0x00158d00094111d7
      friendlyId: sensor-bedroom
      roomId: bedroom
    - deviceId: ZIGBEE-0x00158d00091a41a4
      friendlyId: sensor-bathroom
      roomId: bathroom
    - deviceId: ZIGBEE-0x00158d00091c247e
      friendlyId: sensor-tine
      roomId: tine
    - deviceId: ZIGBEE-0x00158d00091c57e0
      friendlyId: sensor-attic
      roomId: attic
    - deviceId: ZIGBEE-0x00158d00091a40da
      friendlyId: sensor-storage
      roomId: storage
    - deviceId: ZIGBEE-0x00158d00091a4159
      friendlyId: sensor-air-outlet-kitchen
      roomId: kitchen
    - deviceId: ZIGBEE-0x00158d00091a41c8
      friendlyId: sensor-outside
      roomId: outside
    - deviceId: ZIGBEE-0x00158d00091c28de
      friendlyId: sensor-shed
      roomId: shed
    - deviceId: ZIGBEE-0x00158d00091a41b8
      friendlyId: sensor-incubator
      roomId: kitchen
    - deviceId: ZIGBEE-0x00158d0006c4af92
      friendlyId: leak-aquarium
      roomId: livingroom
    - deviceId: ZIGBEE-0x00178801085ff794
      friendlyId: plug
      roomId: livingroom
    - deviceId: LOGO-LIGHT-8256-1
      friendlyId: lights-hallway
      roomId: hallway
    - deviceId: LOGO-LIGHT-8257-2
      friendlyId: lights-garage
      roomId: garage
    - deviceId: HUE-BRIDGE-001788FFFE744E54
      friendlyId: hue-bridge
      roomId: livingroom
    - deviceId: HUE-LIGHT-00:17:88:01:02:fe:89:6d-0b
      friendlyId: light-askel
      roomId: kidsroom
    - deviceId: HUE-LIGHT-00:0d:6f:ff:fe:fb:ee:31-01
      friendlyId: light-kleintje
      roomId: livingroom
    - deviceId: HUE-LIGHT-00:17:88:01:06:26:73:c4-0b
      friendlyId: light-ceiling-kidsroom
      roomId: kidsroom
    - deviceId: HUE-LIGHT-00:17:88:01:06:24:c0:ba-0b
      friendlyId: light-ceiling-kitchen
      roomId: kitchen
    - deviceId: HUE-LIGHT-00:17:88:01:06:51:8d:4f-0b
      friendlyId: light-ceiling-office
      roomId: office
    - deviceId: HUE-LIGHT-00:3c:84:ff:fe:bb:85:63-01
      friendlyId: light-ledstrips-office
      roomId: office
    - deviceId: HUE-SENSOR-00:17:88:01:06:a7:01:de-02-fc00
      friendlyId: dimmer-kidsroom
      roomId: kidsroom
    - deviceId: HUE-SENSOR-00:17:88:01:0c:c3:97:01-01-fc00
      friendlyId: wallswitch-kidsroom
      roomId: kidsroom
    - deviceId: HUE-SENSOR-00:17:88:01:0c:c3:96:f7-01-fc00
      friendlyId: wallswitch-office
      roomId: office
    - deviceId: HUE-SENSOR-00:17:88:01:0d:13:19:dc-01-fc00-0014
      friendlyId: dimmer-office
      roomId: office
    - deviceId: SOLAREDGE-7F165648-33
      friendlyId: solar
      roomId: garage
    - deviceId: ZIGBEE-0xa4c138e1685ab45d
      friendlyId: plug-fridge
      roomId: kitchen
    - deviceId: ZIGBEE-0xa4c138537bf1d92a
      friendlyId: plug-washing-machine
      roomId: laundry
    - deviceId: ZIGBEE-0xa4c138b6d896ab35
      friendlyId: plug-rack
      roomId: attic
    - deviceId: ZIGBEE-0xa4c13891401a35a5
      friendlyId: plug-tv
      roomId: livingroom
    - deviceId: ZIGBEE-0xa4c1383dc2a0e3ea
      friendlyId: plug-office
      roomId: office
    - deviceId: ZIGBEE-0xa4c1385567d073a9
      friendlyId: plug-freezer
      roomId: storage
    - deviceId: TUYA-bfb5c321632e97e066ua7v
      friendlyId: fancoil-office
      roomId: office
    - deviceId: TUYA-bf5c398cf43a8c5cf5q2dm
      friendlyId: fancoil-kidsroom
      roomId: kidsroom
    - deviceId: TUYA-bfc25428abdae57f82kwdp
      friendlyId: fancoil-bedroom
      roomId: bedroom
    - deviceId: TUYA-bfdaafe7a17a881374fwfd
      friendlyId: fancoil-tine
      roomId: tine
deviceConsumers:
  - pushOnOff:
      description: Pushbutton hallway
      configuration:
        pushButtonId: button-hallway
        onOffDeviceId: lights-hallway
  - pushOnOff:
      description: Pushbutton garage
      configuration:
        pushButtonId: button-garage
        onOffDeviceId: lights-garage
  - opsgenieAlarm:
      description: Aquarium leak alarm
      configuration:
        deviceId: leak-aquarium
        property: leak
        value: true
        apiKey: xxx
        responder: Wouter
        message: "AQUARIUM LEAK"
  - influxdbTelemetry:
      description: Send telemetry to InfluxDB
      configuration:
        url: http://192.168.1.180:8086
        token: xxx
        bucket: homesmart
        organization: homesmart
        points:
          - deviceId: sensor-living
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-laundry
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-basement
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-kitchen
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-shaft
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-hallway-downstairs
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-office
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-toilet
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-garage
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-kidsroom
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-bedroom
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-bathroom
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-tine
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-attic
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-storage
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-air-outlet-kitchen
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-outside
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-shed
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: sensor-incubator
            properties: [ 'temperature', 'humidity', 'pressure' ]
          - deviceId: solar
            properties: [ 'lifeTimeEnergy', 'lastYearEnergy', 'lastMonthEnergy', 'lastDayEnergy', 'currentPower', 'previousQuarterEnergy', 'previousQuarterPower' ]
          - deviceId: plug-fridge
            properties: [ 'voltage', 'current', 'power', 'energy' ]
          - deviceId: plug-washing-machine
            properties: [ 'voltage', 'current', 'power', 'energy' ]
          - deviceId: plug-rack
            properties: [ 'voltage', 'current', 'power', 'energy' ]
          - deviceId: plug-tv
            properties: [ 'voltage', 'current', 'power', 'energy' ]
          - deviceId: plug-office
            properties: [ 'voltage', 'current', 'power', 'energy' ]
          - deviceId: plug-freezer
            properties: [ 'voltage', 'current', 'power', 'energy' ]
          - deviceId: fancoil-office
            properties: [ 'temperature', 'requestedTemperature' ]
          - deviceId: fancoil-kidsroom
            properties: [ 'temperature', 'requestedTemperature' ]
          - deviceId: fancoil-bedroom
            properties: [ 'temperature', 'requestedTemperature' ]
          - deviceId: fancoil-tine
            properties: [ 'temperature', 'requestedTemperature' ]
