deviceProviders:
  zigbee:
    ip: 192.168.1.180
    baseTopic: zigbee2mqtt
  logo:
    ip: 192.168.1.200
    port: 510
    pollingInterval: 60000
    outputsAddress: 8192
    switchReturnTime: 100
    devices:
      - name: Lights hallway
        switchAddress: 8256
        outputNumber: 1
      - name: Lights garage
        switchAddress: 8257
        outputNumber: 2
  hue:
    ip: 192.168.1.179
    apiKey: $hueApiKey
  solaredge:
    site: $solaredgeSite
    apiKey: $solaredgeApiKey
  tuya:
    devices:
      - name: Verwarming bureau
        type: fancoil
        ip: 192.168.2.217
        id: bfb5c321632e97e066ua7v
        key: $tuyaApiKeyFancoilOffice
      - name: Verwarming slaapkamer
        type: fancoil
        ip: 192.168.2.197
        id: bfc25428abdae57f82kwdp
        key: $tuyaApiKeyFancoilBedroom
      - name: Verwarming Tine's crib
        type: fancoil
        ip: 192.168.2.193
        id: bfdaafe7a17a881374fwfd
        key: $tuyaApiKeyFancoilTine
      - name: Verwarming kinderkamer
        type: fancoil
        ip: 192.168.2.77
        id: bf5c398cf43a8c5cf5q2dm
        key: $tuyaApiKeyFancoilKidsroom
  somfy:
    ip: 192.168.2.12
  unifi:
    ip: 192.168.1.1
    site: default
    username: api
    password: $unifiPassword
  homewizard:
    pollingInterval: 5
    devices:
      - ip: 192.168.2.194
home:
  rooms:
    - id: livingroom
      name: Living
      type: livingroom
    - id: kitchen
      name: Keuken
      type: kitchen
    - id: kidsroom
      name: Kinderkamer
      type: bedroom
    - id: bedroom
      name: Slaapkamer
      type: bedroom
    - id: tine
      name: Tine's crib
      type: office
    - id: office
      name: Bureau
      type: office
    - id: bathroom
      name: Badkamer
      type: bathroom
    - id: hallway
      name: Hal
      type: hallway
    - id: toilet
      name: WC
      type: toilet
    - id: garage
      name: Garage
      type: garage
    - id: storage
      name: Berging
      type: storage
    - id: laundry
      name: Wasruimte
      type: laundry
    - id: outside
      name: Buiten
      type: outside
    - id: shed
      name: Tuinhuis
      type: shed
    - id: attic
      name: Zolder
      type: attic
    - id: basement
      name: Kelder
      type: basement
    - id: shaft
      name: Koker
      type: other
  devices:
    - deviceId: ZIGBEE-0x00158d0006d0ba73
      friendlyId: button-hallway
      roomId: hallway
    - deviceId: ZIGBEE-0xb4e3f9fffe67d474
      friendlyId: button-garage
      roomId: garage
    - deviceId: ZIGBEE-0x00158d0006c6e6e6
      friendlyId: sensor-living
      roomId: livingroom
    - deviceId: ZIGBEE-0x00158d00091c2406
      friendlyId: sensor-laundry
      roomId: laundry
    - deviceId: ZIGBEE-0x00158d00091a418c
      friendlyId: sensor-basement
      roomId: basement
    - deviceId: ZIGBEE-0x00158d00091ad72f
      friendlyId: sensor-kitchen
      roomId: kitchen
    - deviceId: ZIGBEE-0x00158d00091c22ea
      friendlyId: sensor-shaft
      roomId: shaft
    - deviceId: ZIGBEE-0x00158d000941118d
      friendlyId: sensor-hallway-downstairs
      roomId: hallway
    - deviceId: ZIGBEE-0x00158d00091adbf3
      friendlyId: sensor-office
      roomId: office
    - deviceId: ZIGBEE-0x00158d00091c261d
      friendlyId: sensor-toilet
      roomId: toilet
    - deviceId: ZIGBEE-0x00158d00091c8153
      friendlyId: sensor-garage
      roomId: garage
    - deviceId: ZIGBEE-0x00158d00091a41f9
      friendlyId: sensor-kidsroom
      roomId: kidsroom
    - deviceId: ZIGBEE-0x00158d00094111d7
      friendlyId: sensor-bedroom
      roomId: bedroom
    - deviceId: ZIGBEE-0x00158d00091a41a4
      friendlyId: sensor-bathroom
      roomId: bathroom
    - deviceId: ZIGBEE-0x00158d00091c247e
      friendlyId: sensor-tine
      roomId: tine
    - deviceId: ZIGBEE-0x00158d00091c57e0
      friendlyId: sensor-attic
      roomId: attic
    - deviceId: ZIGBEE-0x00158d00091a40da
      friendlyId: sensor-storage
      roomId: storage
    - deviceId: ZIGBEE-0x00158d00091a4159
      friendlyId: sensor-air-outlet-kitchen
      roomId: kitchen
    - deviceId: ZIGBEE-0x00158d00091a41c8
      friendlyId: sensor-outside
      roomId: outside
    - deviceId: ZIGBEE-0x00158d00091c28de
      friendlyId: sensor-shed
      roomId: shed
    - deviceId: ZIGBEE-0x00158d00091a41b8
      friendlyId: sensor-incubator
      roomId: kitchen
    - deviceId: ZIGBEE-0x00158d00091c2645
      friendlyId: sensor-small-incubator
      roomId: kitchen
    - deviceId: ZIGBEE-0x00158d00091c22e3
      friendlyId: sensor-rack
      roomId: attic
    - deviceId: ZIGBEE-0x00158d0006c4af92
      friendlyId: leak-aquarium
      roomId: livingroom
    - deviceId: ZIGBEE-0x00178801085ff794
      friendlyId: plug
      roomId: livingroom
      alternateName: Kerstboom
      alternateIcon: tree
      hideWhenUnreachable: true
    - deviceId: LOGO-LIGHT-8256-1
      friendlyId: lights-hallway
      roomId: hallway
    - deviceId: LOGO-LIGHT-8257-2
      friendlyId: lights-garage
      roomId: garage
    - deviceId: HUE-BRIDGE-001788FFFE744E54
      friendlyId: hue-bridge
      roomId: livingroom
    - deviceId: HUE-LIGHT-00:17:88:01:02:fe:89:6d
      friendlyId: light-askel
      roomId: kidsroom
    - deviceId: HUE-LIGHT-00:0d:6f:ff:fe:fb:ee:31
      friendlyId: light-kleintje
      roomId: livingroom
    - deviceId: HUE-LIGHT-00:17:88:01:06:26:73:c4
      friendlyId: light-ceiling-kidsroom
      roomId: kidsroom
    - deviceId: HUE-LIGHT-00:17:88:01:06:24:c0:ba
      friendlyId: light-ceiling-kitchen
      roomId: kitchen
    - deviceId: HUE-LIGHT-00:17:88:01:06:51:8d:4f
      friendlyId: light-ceiling-office
      roomId: office
    - deviceId: HUE-LIGHT-00:3c:84:ff:fe:bb:85:63
      friendlyId: light-ledstrips-office
      roomId: office
    - deviceId: HUE-SENSOR-00:17:88:01:06:a7:01:de
      friendlyId: dimmer-kidsroom
      roomId: kidsroom
    - deviceId: HUE-SENSOR-00:17:88:01:0c:c3:97:01
      friendlyId: wallswitch-kidsroom
      roomId: kidsroom
    - deviceId: HUE-SENSOR-00:17:88:01:0c:c3:96:f7
      friendlyId: wallswitch-office
      roomId: office
    - deviceId: HUE-SENSOR-00:17:88:01:0d:13:19:dc
      friendlyId: dimmer-office
      roomId: office
    - deviceId: SOLAREDGE-7F165648-33
      friendlyId: solar
      roomId: garage
    - deviceId: ZIGBEE-0xa4c138e1685ab45d
      friendlyId: plug-fridge
      roomId: kitchen
    - deviceId: ZIGBEE-0xa4c138537bf1d92a
      friendlyId: plug-washing-machine
      roomId: laundry
    - deviceId: ZIGBEE-0xa4c138b6d896ab35
      friendlyId: plug-rack
      roomId: attic
    - deviceId: ZIGBEE-0xa4c13891401a35a5
      friendlyId: plug-tv
      roomId: livingroom
    - deviceId: ZIGBEE-0xa4c1383dc2a0e3ea
      friendlyId: plug-office
      roomId: office
    - deviceId: ZIGBEE-0xa4c13859bde770fd
      friendlyId: plug-freezer
      roomId: storage
    - deviceId: ZIGBEE-0xa4c138c05c91221b
      friendlyId: plug-rainwater-pump
      roomId: garage
    - deviceId: ZIGBEE-0xa4c138a935df171a
      friendlyId: plug-dishwasher
      roomId: kitchen
    - deviceId: ZIGBEE-0xa4c138b4f04bfd71
      friendlyId: plug-vacuum
      roomId: kitchen
    - deviceId: ZIGBEE-0xa4c138a5763339d3
      friendlyId: plug-aquarium
      roomId: livingroom
    - deviceId: TUYA-bfb5c321632e97e066ua7v
      friendlyId: fancoil-office
      roomId: office
    - deviceId: TUYA-bf5c398cf43a8c5cf5q2dm
      friendlyId: fancoil-kidsroom
      roomId: kidsroom
    - deviceId: TUYA-bfc25428abdae57f82kwdp
      friendlyId: fancoil-bedroom
      roomId: bedroom
    - deviceId: TUYA-bfdaafe7a17a881374fwfd
      friendlyId: fancoil-tine
      roomId: tine
    - deviceId: ZIGBEE-0x18fc260000084fd9
      friendlyId: trv-bathroom
      roomId: bathroom
    - deviceId: ZIGBEE-0x0017880104f7dd5d
      friendlyId: dimmer-bathroom
      roomId: bathroom
    - deviceId: SOMFY-BRIDGE
      friendlyId: somfy-bridge
      roomId: livingroom
    - deviceId: SOMFY-SHUTTER-1
      friendlyId: shutter-living-side-back
      roomId: livingroom
    - deviceId: SOMFY-REMOTE-13628768
      friendlyId: somfy-remote-living-side-back
      roomId: livingroom
    - deviceId: SOMFY-SHUTTER-2
      friendlyId: shutter-living-side-front
      roomId: livingroom
    - deviceId: SOMFY-REMOTE-5109344
      friendlyId: somfy-remote-living-side-front
      roomId: livingroom
    - deviceId: SOMFY-SHUTTER-3
      friendlyId: shutter-living-front
      roomId: livingroom
    - deviceId: SOMFY-REMOTE-657249
      friendlyId: somfy-remote-living-front
      roomId: livingroom
    - deviceId: SOMFY-SHUTTER-5
      friendlyId: shutter-living-back
      roomId: livingroom
    - deviceId: SOMFY-REMOTE-9418844
      friendlyId: somfy-remote-living-back
      roomId: livingroom
    - deviceId: SOMFY-SHUTTER-4
      friendlyId: shutter-office
      roomId: office
    - deviceId: SOMFY-REMOTE-11925856
      friendlyId: somfy-remote-office
      roomId: office
    - deviceId: SOMFY-SHUTTER-6
      friendlyId: shutter-kitchen-window
      roomId: kitchen
    - deviceId: SOMFY-REMOTE-264033
      friendlyId: somfy-remote-kitchen-window
      roomId: kitchen
    - deviceId: SOMFY-SHUTTER-7
      friendlyId: shutter-kitchen-door
      roomId: kitchen
    - deviceId: SOMFY-REMOTE-13432160
      friendlyId: somfy-remote-kitchen-door
      roomId: kitchen
    - deviceId: SOMFY-REMOTE-9620325
      friendlyId: somfy-timer
      roomId: kitchen
    - deviceId: UNIFI-PROTECT-f4:e2:c6:77:80:f3
      friendlyId: camera-back
      roomId: outside
    - deviceId: UNIFI-PROTECT-f4:e2:c6:77:80:25
      friendlyId: camera-side
      roomId: outside
    - deviceId: UNIFI-PROTECT-f4:e2:c6:77:80:b2
      friendlyId: camera-front
      roomId: outside
    - deviceId: UNIFI-NETWORK-646b87cf68e8c417eb9be4de
      friendlyId: network-udm
      roomId: attic
    - deviceId: UNIFI-NETWORK-646b892e68e8c417eb9be511
      friendlyId: network-switch-office
      roomId: office
    - deviceId: UNIFI-NETWORK-646b892e68e8c417eb9be515
      friendlyId: network-ap-hallway
      roomId: hallway
    - deviceId: UNIFI-NETWORK-646b892e68e8c417eb9be514
      friendlyId: network-switch-garage
      roomId: garage
    - deviceId: UNIFI-NETWORK-646b892e68e8c417eb9be512
      friendlyId: network-switch-livingroom
      roomId: livingroom
    - deviceId: UNIFI-NETWORK-65de63da9204f15f54fc8416
      friendlyId: network-switch-poe
      roomId: attic
    - deviceId: UNIFI-NETWORK-646b892e68e8c417eb9be513
      friendlyId: network-ap-office
      roomId: office
    - deviceId: UNIFI-NETWORK-646b892e68e8c417eb9be519
      friendlyId: network-ap-livingroom
      roomId: livingroom
    - deviceId: HW-WATER-5c2faf1940c2
      friendlyId: watermeter
      roomId: garage  
automations:
  - pushOnOff:
      description: Pushbutton hallway
      configuration:
        pushButtonId: button-hallway
        onOffDeviceId: lights-hallway
  - pushOnOff:
      description: Pushbutton garage
      configuration:
        pushButtonId: button-garage
        onOffDeviceId: lights-garage
  - opsgenieAlarm:
      description: Aquarium leak alarm
      configuration:
        deviceId: leak-aquarium
        property: leak
        value: true
        apiKey: $opsgenieApiKey
        responder: Wouter
        priority: P1
        message: "AQUARIUM LEAK"
  - opsgenieAlarm:
      description: Laundry done alert
      configuration:
        deviceId: plug-washing-machine
        property: active
        value: false
        apiKey: $opsgenieApiKey
        responder: Wouter
        priority: P5
        message: "De wasmachine is klaar"
        rateLimit: 15m
  - dimmerHeating:
      description: Remote heater bathroom
      configuration:
        dimmerId: dimmer-bathroom
        heaterId: trv-bathroom
telemetry:
  influx:
    url: http://192.168.1.180:8086
    token: $influxdbToken
    bucket: homesmart
    organization: homesmart
    data:
      - deviceIds: 
          - sensor-living
          - sensor-laundry
          - sensor-basement
          - sensor-kitchen
          - sensor-shaft
          - sensor-hallway-downstairs
          - sensor-office
          - sensor-toilet
          - sensor-garage
          - sensor-kidsroom
          - sensor-bedroom
          - sensor-bathroom
          - sensor-tine
          - sensor-attic
          - sensor-storage
          - sensor-air-outlet-kitchen
          - sensor-outside
          - sensor-shed
          - sensor-incubator
          - sensor-small-incubator
          - sensor-rack
        properties: 
          - temperature
          - humidity
          - pressure
      - deviceIds: 
          - solar
        properties: 
          - lifeTimeEnergy
          - lastYearEnergy
          - lastMonthEnergy
          - lastDayEnergy
          - currentPower
          - previousQuarterEnergy
          - previousQuarterPower
      - deviceIds: 
          - plug-fridge
          - plug-washing-machine
          - plug-rack
          - plug-tv
          - plug-office
          - plug-freezer
          - plug-rainwater-pump
          - plug-dishwasher
          - plug-vacuum
          - plug-aquarium
        properties: 
          - voltage
          - current
          - power
          - energy
      - deviceIds: 
          - fancoil-office
          - fancoil-kidsroom
          - fancoil-bedroom
          - fancoil-tine
          - trv-bathroom
        properties: 
          - temperature
          - requestedTemperature
      - deviceIds: 
          - watermeter
        properties: 
          - totalLiters
          - litersPerMinute
remote:
  azure:
    apiUrl: http://huis.wouterdevinck.be/api/v1/
    iot: 
      host: wouter.azure-devices.net
      id: test2
      key: $iotKey
    notifications:
      host: wouter.service.signalr.net
      key: $notificationsKey