deviceProviders:
  zigbee:
    ip: 192.168.1.180
    baseTopic: zigbee2mqtt
  logo:
    ip: 192.168.1.200
    port: 510
    pollingInterval: 60000
    outputsAddress: 8192
    switchReturnTime: 100
    devices:
      - name: Lights hallway
        switchAddress: 8256
        outputNumber: 1
      - name: Lights garage
        switchAddress: 8257
        outputNumber: 2
  hue:
    apiKey: xxx
    polling:
      minPollInterval: 1000
      maxPollInterval: 60000
      backOffInterval: 120000
      backOffFactor: 2
devices:
  - deviceId: ZIGBEE-0x00158d0006d0ba73
    friendlyId: button-hallway
  - deviceId: ZIGBEE-0xb4e3f9fffe67d474
    friendlyId: button-garage
  - deviceId: LOGO-LIGHT-8256-1
    friendlyId: lights-hallway
  - deviceId: LOGO-LIGHT-8257-2
    friendlyId: lights-garage
  - deviceId: ZIGBEE-0x00158d0006c6e6e6
    friendlyId: sensor-living
  - deviceId: ZIGBEE-0x00158d0006c4af92
    friendlyId: leak-aquarium
automations:
  - pushOnOff:
      description: Pushbutton hallway
      configuration:
        pushButtonId: button-hallway
        onOffDeviceId: lights-hallway
  - pushOnOff:
      description: Pushbutton garage
      configuration:
        pushButtonId: button-garage
        onOffDeviceId: lights-garage
  - opsgenieAlarm:
      description: Aquarium leak alarm
      configuration:
        deviceId: leak-aquarium
        property: leak
        value: true
        apiKey: xxx
        responder: Wouter
        message: "AQUARIUM LEAK"
telemetry:
  influxdb:
    url: http://192.168.1.180:8086
    token: xxx
    points:
      - deviceId: sensor-living
        properties: [ 'temperature', 'humidity', 'pressure' ]