version: "3.9"
services:
  homesmart:
    image: wouterdevinck/homesmart
    ports:
      - 80:5000
    volumes:
      - homesmart:/data
    environment:
      - HOME_CONFIG=/data/config.yaml
      - HOME_SECRETS=/data/secrets.yaml
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:2.21.2
    ports:
      - 9000:9000
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    ports:
      - 1883:1883
    volumes:
      - mosquitto:/mosquitto
    restart: unless-stopped
  zigbee:
    image: koenkk/zigbee2mqtt:1.40.1
    ports:
      - 8080:8080
    volumes:
      - zigbee:/app/data
    environment:
      - TZ=Europe/Brussels
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
  influxdb:
    image: influxdb:2.7.10
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    restart: unless-stopped
volumes:
  homesmart:
  portainer:
  mosquitto:
  zigbee:
  influxdb-data:
  influxdb-config: