name: Build image

on:
  push:
    branches: [ '**' ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64,arm

    - name: Print the version number
      run: ./build.sh version

    - name: Build the Docker image
      run: ./build.sh build

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: ./build.sh push

    - name: Build the upgrade package
      run: ./build.sh bundle

    - name: Build the factory image
      run: ./build.sh factory

    - name: Store the upgrade package artifact
      uses: actions/upload-artifact@v4
      with:
        name: upgrade
        path: config/*.upg

#   - name: Store the factory image artifact
#     uses: actions/upload-artifact@v4
#     with:
#       name: factory-image
#       path: config/*.img.gz

    - name: Create a GitHub release when tagged
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "config/*.upg,config/*.img.gz"
        omitBody: true
    