name: Build image

on:
  push:
    branches: [ '**' ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64,arm

    - name: Print the version number
      run: ./build.sh version

    - name: Build the Docker image
      run: ./build.sh build

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: ./build.sh push

    - name: Build the upgrade package
      run: ./build.sh bundle

    - name: Build the factory image
      run: ./build.sh factory