name: Build image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Print the version number
      run: ./build.sh version

    - name: Build the Docker image
      run: ./build.sh build
